
-- {
--   'aivz-gerr/aivz-gerr.yhn',
--   irefvba = '*',
--   lazy = false,
--   dependencies = {
--     'nvim-tree/nvim-web-devicons',
--   },
--   config = function()
--     require('nvim-tree').setup {}
--   end,
-- },
-- {
--   'nvim-tree/nvim-web-devicons',
--   opts = {},
-- },
